ALTER TABLE TUNNELS ADD COLUMN SOURCE_INTERFACE VARCHAR(255) DEFAULT '127.0.0.1';
ALTER TABLE TUNNELS DROP COLUMN ALLOW_EXTERNAL_HOSTS;

ALTER TABLE TUNNELS DROP COLUMN PARENT_RESOURCE_PERMISSION;

ALTER TABLE TUNNELS ADD COLUMN REALM_ID INTEGER DEFAULT 1;
