//
// Roles
//

CREATE CACHED TABLE ROLES
(
   ROLENAME VARCHAR(255) PRIMARY KEY
);

INSERT INTO ROLES (ROLENAME) VALUES ('Users');

//
// Users
//

CREATE CACHED TABLE USERS
(
   USERNAME VARCHAR(255) PRIMARY KEY,
   EMAIL VARCHAR(255) not null,
   FULLNAME VARCHAR(255) not null,
   LAST_PASSWORD_CHANGE DATE,
   PASSWORD VARCHAR(100)
);

//
// User roles
//

CREATE CACHED TABLE USER_ROLES
(
   USERNAME VARCHAR(255) not null,
   ROLENAME VARCHAR(255) not null
);


CREATE UNIQUE INDEX SYS_IDX_USER_ROLES_CONSTRAINT_4 ON USER_ROLES
(
  USERNAME,
  ROLENAME
);