INSERT INTO EXPLORER_PROPERTY_DEFINITION (NAME,VISIBILITY,TYPE,SORT_ORDER,TYPE_META,CATEGORY,DEFAULT_VALUE,HIDDEN) VALUES ('webforward.activeDNSFormat',2,3,100,'1,2',90,'1',0);
INSERT INTO EXPLORER_PROPERTY_DEFINITION (NAME,VISIBILITY,TYPE,SORT_ORDER,TYPE_META,CATEGORY,DEFAULT_VALUE,HIDDEN) VALUES ('security.enforce.policy.resource.access',2,2,10,'',55,'false',0);
DELETE FROM EXPLORER_PROPERTY_DEFINITION WHERE NAME = 'authenticationScheme.default';
