ALTER TABLE APPLICATION_SHORTCUTS DROP COLUMN PARENT_RESOURCE_PERMISSION;

ALTER TABLE APPLICATION_SHORTCUTS ADD COLUMN REALM_ID INTEGER DEFAULT 1;

UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-advancednativerdpwin32' WHERE APPLICATION = 'AdvancedNativeRDPWin32';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-nx' WHERE APPLICATION = 'nxclient';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-putty' WHERE APPLICATION = 'PuTTY';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-rdesktop' WHERE APPLICATION = 'rdesktop';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-rdp' WHERE APPLICATION = 'RDP';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-tn3250' WHERE APPLICATION = 'TN5250j';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-ultravnc' WHERE APPLICATION = 'UltraVNC';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-vnc' WHERE APPLICATION = 'VNC';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-winscp' WHERE APPLICATION = 'WinSCP';
UPDATE APPLICATION_SHORTCUTS SET APPLICATION = 'openvpnals-application-wolwindowsnative' WHERE APPLICATION = 'WOLWindowsNative';

