UPDATE POLICY SET POLICY_DESCRIPTION = 'This special system-wide policy includes all users and roles by default. You can neither delete this policy nor change the principals attached.' WHERE POLICY_NAME = 'Everyone'

-- Add principal type to the policy principal relationship key

CREATE CACHED TABLE TMP_POLICY_PRINCIPAL_RELATIONSHIP
(
   POLICY_ID INTEGER not null,
   PRINCIPAL_ID VARCHAR(2147483647) not null,
   PRINCIPAL_TYPE INTEGER not null
);
INSERT INTO TMP_POLICY_PRINCIPAL_RELATIONSHIP SELECT * FROM POLICY_PRINCIPAL_RELATIONSHIP ;
DROP TABLE POLICY_PRINCIPAL_RELATIONSHIP;
CREATE CACHED TABLE POLICY_PRINCIPAL_RELATIONSHIP
(
   POLICY_ID INTEGER not null,
   PRINCIPAL_ID VARCHAR(2147483647) not null,
   PRINCIPAL_TYPE INTEGER not null,
   CONSTRAINT POLICY_PRINCIPAL_RELATIONSHIP_PK PRIMARY KEY (POLICY_ID,PRINCIPAL_ID,PRINCIPAL_TYPE)
);
INSERT INTO POLICY_PRINCIPAL_RELATIONSHIP SELECT * FROM TMP_POLICY_PRINCIPAL_RELATIONSHIP ;
DROP TABLE TMP_POLICY_PRINCIPAL_RELATIONSHIP;