ALTER TABLE POLICY_RESOURCE_RELATIONSHIP ADD COLUMN SEQUENCE INTEGER;

INSERT INTO POLICY_RESOURCE_RELATIONSHIP (RESOURCE_ID,POLICY_ID,RESOURCE_TYPE) VALUES (1,0,1003);
INSERT INTO POLICY_RESOURCE_RELATIONSHIP (RESOURCE_ID,POLICY_ID,RESOURCE_TYPE) VALUES (2,0,1003);
INSERT INTO POLICY_RESOURCE_RELATIONSHIP (RESOURCE_ID,POLICY_ID,RESOURCE_TYPE) VALUES (3,0,1003);
INSERT INTO POLICY_RESOURCE_RELATIONSHIP (RESOURCE_ID,POLICY_ID,RESOURCE_TYPE) VALUES (4,0,1003);
