ALTER TABLE AUTH_SCHEMES ADD COLUMN PRIORITY INTEGER;

UPDATE AUTH_SCHEMES SET PRIORITY = '1' WHERE RESOURCE_ID = '1';
UPDATE AUTH_SCHEMES SET PRIORITY = '2' WHERE RESOURCE_ID = '2';
UPDATE AUTH_SCHEMES SET PRIORITY = '9998' WHERE RESOURCE_ID = '3';
UPDATE AUTH_SCHEMES SET PRIORITY = '9999' WHERE RESOURCE_ID = '4';